/* Automatically generated by svg npm script */

import React from 'react';

function Bookmark(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M11 8v22l7-5 7 5V8z" />
    </svg>
  );
}

export default Bookmark;
