/* Automatically generated by svg npm script */

import React from 'react';

function PlayArrow(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M12 9v18l15-9z" />
    </svg>
  );
}

export default PlayArrow;
