/* Automatically generated by svg npm script */

import React from 'react';

function ResizeEw(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M20 18h6v3l5-4-5-4v3H8v-3l-5 4 5 4v-3z" />
    </svg>
  );
}

export default ResizeEw;
