/* Automatically generated by svg npm script */

import React from 'react';

function ResizeNesw(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M19.414 16.586l4.243-4.243 2.121 2.121.707-6.363-6.364.707 2.122 2.12L9.515 23.658l-2.122-2.121-.707 6.363 6.364-.707-2.121-2.12z" />
    </svg>
  );
}

export default ResizeNesw;
