/* Automatically generated by svg npm script */

import React from 'react';

function ResizeNwse(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M16.586 16.586l-4.243-4.243 2.121-2.121-6.363-.707.707 6.364 2.12-2.122 12.729 12.728-2.121 2.122 6.363.707-.707-6.364-2.12 2.121z" />
    </svg>
  );
}

export default ResizeNwse;
