/* Automatically generated by svg npm script */

import React from 'react';

function SkipPrevious(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M30 27V9l-10 9zM20 27V9l-10 9zM10 27V9H6v18z" />
    </svg>
  );
}

export default SkipPrevious;
