/* Automatically generated by svg npm script */

import React from 'react';

function SkipNext(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 36 36" width="1em" height="1em" {...props}>
      <path d="M6 9v18l10-9zM16 9v18l10-9zM26 9v18h4V9z" />
    </svg>
  );
}

export default SkipNext;
