function template(
  { template },
  opts,
  { imports, componentName, jsx, exports }
) {
  const typeScriptTpl = template.smart({ plugins: ['typescript'] });

  return typeScriptTpl.ast`/* Automatically generated by svg npm script */
    ${imports}

    function ${componentName}(props: React.SVGAttributes<SVGSVGElement>) {
      return ${jsx}
    }

    ${exports}
`;
}

module.exports = template;
