import {
  AVAILABLE_PLAYBACK_RATES,
  AVAILABLE_THEMES,
  AVAILABLE_LANGUAGES,
  SELECTABLE_FONT_FACES,
  FONT_SIZE_MULTIPLIERS,
  SELECTABLE_LINE_HEIGHTS
} from '.';
import {
  DEFAULT_FONT_FACE,
  DEFAULT_FONT_UPPERCASE,
  DEFAULT_FONT_SIZE_MULTIPLIER,
  DEFAULT_LANG,
  DEFAULT_LINE_HEIGHT,
  DEFAULT_PREVIOUS_CHAPTER_SEEK_THRESHOLD,
  DEFAULT_SEEK_STEP,
  DEFAULT_SEEK_STEP_MULTIPLIER,
  DEFAULT_TEXT_HIGHLIGHTING,
  DEFAULT_THEME,
  DEFAULT_VOLUME_STEP,
  DEFAULT_VOLUME_STEP_MULTIPLIER
} from './preferences';
import { DEFAULT_WIDGETS } from './widgets';
import { IPreferencesState } from '../reducers/preferences';

export const initialPreferencesState: IPreferencesState = {
  fontFace: DEFAULT_FONT_FACE,
  fontFaces: SELECTABLE_FONT_FACES,
  fontSizeMultiplier: DEFAULT_FONT_SIZE_MULTIPLIER,
  fontSizeMultipliers: FONT_SIZE_MULTIPLIERS,
  fontUppercase: DEFAULT_FONT_UPPERCASE,
  language: DEFAULT_LANG,
  languages: AVAILABLE_LANGUAGES,
  lineHeight: DEFAULT_LINE_HEIGHT,
  lineHeightValues: SELECTABLE_LINE_HEIGHTS,
  playbackRates: AVAILABLE_PLAYBACK_RATES,
  previousChapterSeekThreshold: DEFAULT_PREVIOUS_CHAPTER_SEEK_THRESHOLD,
  seekStep: DEFAULT_SEEK_STEP,
  seekStepMultiplier: DEFAULT_SEEK_STEP_MULTIPLIER,
  textHighlighting: DEFAULT_TEXT_HIGHLIGHTING,
  theme: DEFAULT_THEME,
  themes: AVAILABLE_THEMES,
  volumeStep: DEFAULT_VOLUME_STEP,
  volumeStepMultiplier: DEFAULT_VOLUME_STEP_MULTIPLIER,
  widgets: DEFAULT_WIDGETS
};
