baseURL = "https://inria.github.io/aiana-player/"
languageCode = "en-us"
title = "Aiana Player Documentation"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap", "RSS"]

[params]
description = "Documentation description"
